### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by Camble** [Camble/Safe-Power-Monitor#2]
System slows to a crawl when batteryGPIO is set to anything other than None.

**Comment by Camble** [comment]
Removed reference to old BatteryWatcher class 24b837bb0bb801d12a59e2f6bba184511f8f1b13

**Comment by austinmini75** [comment]
Further to Cambles comment, when connected to the mains system works perfectly

**Comment by Camble** [comment]
@austinmini75 Thanks, I didn't expect that. Are you able to test using the refactor branch?

`git pull origin refactor; git checkout refactor`

**Comment by austinmini75** [comment]
What does that do please?

**Comment by Camble** [comment]
It will pull down the changes I've made to see if it resolves the issue.

**Comment by austinmini75** [comment]
Thanks for the reply, I used "cd ~/Safe-Power-Monitor;git pull origin master" does this do the same please?

**Comment by Camble** [comment]
No :)

**Comment by austinmini75** [comment]
thanks will update here asap

**Comment by austinmini75** [comment]
Hi trying to run "git pull origin refactor; git checkout refactor" but it does not seem to be working please help:

```
pi@retropie:~/Safe-Power-Monitor $ sudo git pull origin refactor; git checkout r                            efactor
From https://github.com/Camble/Safe-Power-Monitor
 * branch            refactor   -> FETCH_HEAD
Updating 461e453..24b837b
error: Your local changes to the following files would be overwritten by merge:
        safe_power_monitor.py
Please, commit your changes or stash them before you can merge.
Aborting
error: Your local changes to the following files would be overwritten by checkou                            t:
        safe_power_monitor.py
Please, commit your changes or stash them before you can switch branches.
Aborting
```

**Comment by austinmini75** [comment]
never mind i managed - what can i expect now please?

**Comment by austinmini75** [comment]
I edited the script to "False" next to Adafruit powerboost as i have a generic powerboost from banggood and reset the system. So far no lag but its no longer safe shutting down when i slide switch to off

**Comment by Camble** [comment]
@austinmini75 I suggest you go back to using the master branch. This issue is for the PowerBoost. If you're having trouble with any other aspect of the Safe Shutdown, you can contact me on Discord or the Sudomod forum.

**Comment by austinmini75** [comment]
So this is not for the generic powerboost?, im sorry then i really dont know what i should be doing: so i run:
git pull origin refactor; git checkout refactor

what does this do, what do i do after i run it, what is a master branch

**Comment by Camble** [comment]
`git checkout master`

**Comment by austinmini75** [comment]
Thanks, but what exactly does it do and is it for the generic powerboost?

**Comment by austinmini75** [comment]
`pi@retropie:~/Safe-Power-Monitor $ git pull origin master; git checkout master
From https://github.com/Camble/Safe-Power-Monitor
 * branch            master     -> FETCH_HEAD
Already up-to-date.
M       safe_power_monitor.py
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
`

**Comment by Camble** [comment]
Please read the readme. This thread is not for your issue.
