### ISSUE TITLE
The dtoverlay check is a bit simple and can break existing overlay settings

### ISSUE THREAD

**Issue by FraserChapman** [Camble/Safe-Power-Monitor#6]
# Check /boot/config.txt for dtoverlay line, and add it if required

If I have the line: dtoverlay=t1,t2 

This script will add a new dtoverlay line, leaving two dtoverlay settings. i.e.

dtoverlay=t2,t2
dtoverlay=gpio-poweroff,gpiopin=22,active_low="y"

Disabling/overwriting what is currently set.

Really what it should do is rather than looking for the "new line" is

1) check if any line starts with "dtoverlay="
2) if it does CSV parse the values
3) iterate each the values - check if gpiopin=22, active_low="y", etc
4) add missing settings existing dtoverlay string as required
5) else add the whole new dtoverlay setting (as already done)

So you end up with 

dtoverlay=t2,t2,gpio-poweroff,gpiopin=22,active_low="y"

--

Hope that makes sense! Great board and great script too :)

**Comment by Camble** [comment]
Thanks, I'll look into this.

**Comment by Camble** [comment]
After investigation, the Raspberry Pi documentation would suggest it's fine to have multiple dtoverlay lines in the config.txt file.

**Comment by FraserChapman** [comment]
Hey, yes I came to that conclusion too - sorry for the mistake!
