### ISSUE TITLE
Prevent kernel panic

### ISSUE THREAD

**Issue by dbrock89** [Camble/Safe-Power-Monitor#9]
Dtoverlay line has the incorrect punctuation mark causing kernel panics when using normal shutdown command.

Should be as follows:

dtoverlay=gpio-poweroff:gpiopin="22",active_low="y"

**Comment by Camble** [comment]
I'm not sure this is really an issue but I've added quotation marks anyway.

**Comment by Camble** [comment]
I'm unable to find any documentation to support the requirement for a colon after poweroff, or quotes around the gpio pin. Can you provide a link?

**Comment by Camble** [comment]
Scratch that, I've found the documentation
